services:
  wallet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-app
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app
    env_file:
      - .env

networks:
  app:
    driver: bridge
